flags:
  monad-logger-syslog: {}
packages:
- '.'
extra-deps: []

resolver: lts-23.9
# resolver: lts-22.43
# resolver: lts-16.26
# resolver: lts-14.15
# resolver: lts-13.19
# resolver: lts-12.26
# resolver: lts-11.22
# resolver: lts-9.21
# resolver: lts-7.24
